require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LinkClicksController do

  # This should return the minimal set of attributes required to create a valid
  # LinkClick. As you add validations to LinkClick, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { FactoryGirl.build(:link_click).attributes }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LinkClicksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all link_clicks as @link_clicks" do
      link_click = LinkClick.create! valid_attributes
      get :index, {}, valid_session
      assigns(:link_clicks).should eq([link_click])
    end
  end

  describe "GET show" do
    it "assigns the requested link_click as @link_click" do
      link_click = LinkClick.create! valid_attributes
      get :show, {:id => link_click.to_param}, valid_session
      assigns(:link_click).should eq(link_click)
    end
  end

  describe "GET new" do
    it "assigns a new link_click as @link_click" do
      get :new, {}, valid_session
      assigns(:link_click).should be_a_new(LinkClick)
    end
  end

  describe "GET edit" do
    it "assigns the requested link_click as @link_click" do
      link_click = LinkClick.create! valid_attributes
      get :edit, {:id => link_click.to_param}, valid_session
      assigns(:link_click).should eq(link_click)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LinkClick" do
        expect {
          post :create, {:link_click => valid_attributes}, valid_session
        }.to change(LinkClick, :count).by(1)
      end

      it "assigns a newly created link_click as @link_click" do
        post :create, {:link_click => valid_attributes}, valid_session
        assigns(:link_click).should be_a(LinkClick)
        assigns(:link_click).should be_persisted
      end

      it "redirects to the created link_click" do
        post :create, {:link_click => valid_attributes}, valid_session
        response.should redirect_to(LinkClick.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved link_click as @link_click" do
        # Trigger the behavior that occurs when invalid params are submitted
        LinkClick.any_instance.stub(:save).and_return(false)
        post :create, {:link_click => { "app_link_id" => "invalid value" }}, valid_session
        assigns(:link_click).should be_a_new(LinkClick)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LinkClick.any_instance.stub(:save).and_return(false)
        post :create, {:link_click => { "app_link_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested link_click" do
        link_click = LinkClick.create! valid_attributes
        # Assuming there are no other link_clicks in the database, this
        # specifies that the LinkClick created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LinkClick.any_instance.should_receive(:update).with({ "app_link_id" => "1" })
        put :update, {:id => link_click.to_param, :link_click => { "app_link_id" => "1" }}, valid_session
      end

      it "assigns the requested link_click as @link_click" do
        link_click = LinkClick.create! valid_attributes
        put :update, {:id => link_click.to_param, :link_click => valid_attributes}, valid_session
        assigns(:link_click).should eq(link_click)
      end

      it "redirects to the link_click" do
        link_click = LinkClick.create! valid_attributes
        put :update, {:id => link_click.to_param, :link_click => valid_attributes}, valid_session
        response.should redirect_to(link_click)
      end
    end

    describe "with invalid params" do
      it "assigns the link_click as @link_click" do
        link_click = LinkClick.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LinkClick.any_instance.stub(:save).and_return(false)
        put :update, {:id => link_click.to_param, :link_click => { "app_link_id" => "invalid value" }}, valid_session
        assigns(:link_click).should eq(link_click)
      end

      it "re-renders the 'edit' template" do
        link_click = LinkClick.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LinkClick.any_instance.stub(:save).and_return(false)
        put :update, {:id => link_click.to_param, :link_click => { "app_link_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested link_click" do
      link_click = LinkClick.create! valid_attributes
      expect {
        delete :destroy, {:id => link_click.to_param}, valid_session
      }.to change(LinkClick, :count).by(-1)
    end

    it "redirects to the link_clicks list" do
      link_click = LinkClick.create! valid_attributes
      delete :destroy, {:id => link_click.to_param}, valid_session
      response.should redirect_to(link_clicks_url)
    end
  end

end
