require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MobileAppsController do

  # This should return the minimal set of attributes required to create a valid
  # MobileApp. As you add validations to MobileApp, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { FactoryGirl.build(:mobile_app).attributes }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MobileAppsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mobile_apps as @mobile_apps" do
      mobile_app = MobileApp.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mobile_apps).should eq([mobile_app])
    end
  end

  describe "GET show" do
    it "assigns the requested mobile_app as @mobile_app" do
      mobile_app = MobileApp.create! valid_attributes
      get :show, {:id => mobile_app.to_param}, valid_session
      assigns(:mobile_app).should eq(mobile_app)
    end
  end

  describe "GET new" do
    it "assigns a new mobile_app as @mobile_app" do
      get :new, {}, valid_session
      assigns(:mobile_app).should be_a_new(MobileApp)
    end
  end

  describe "GET edit" do
    it "assigns the requested mobile_app as @mobile_app" do
      mobile_app = MobileApp.create! valid_attributes
      get :edit, {:id => mobile_app.to_param}, valid_session
      assigns(:mobile_app).should eq(mobile_app)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MobileApp" do
        expect {
          post :create, {:mobile_app => valid_attributes}, valid_session
        }.to change(MobileApp, :count).by(1)
      end

      it "assigns a newly created mobile_app as @mobile_app" do
        post :create, {:mobile_app => valid_attributes}, valid_session
        assigns(:mobile_app).should be_a(MobileApp)
        assigns(:mobile_app).should be_persisted
      end

      it "redirects to the created mobile_app" do
        post :create, {:mobile_app => valid_attributes}, valid_session
        response.should redirect_to(MobileApp.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mobile_app as @mobile_app" do
        # Trigger the behavior that occurs when invalid params are submitted
        MobileApp.any_instance.stub(:save).and_return(false)
        post :create, {:mobile_app => { "name" => "invalid value" }}, valid_session
        assigns(:mobile_app).should be_a_new(MobileApp)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MobileApp.any_instance.stub(:save).and_return(false)
        post :create, {:mobile_app => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mobile_app" do
        mobile_app = MobileApp.create! valid_attributes
        # Assuming there are no other mobile_apps in the database, this
        # specifies that the MobileApp created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MobileApp.any_instance.should_receive(:update).with({ "name" => "" })
        put :update, {:id => mobile_app.to_param, :mobile_app => { "name" => "" }}, valid_session
      end

      it "assigns the requested mobile_app as @mobile_app" do
        mobile_app = MobileApp.create! valid_attributes
        put :update, {:id => mobile_app.to_param, :mobile_app => valid_attributes}, valid_session
        assigns(:mobile_app).should eq(mobile_app)
      end

      it "redirects to the mobile_app" do
        mobile_app = MobileApp.create! valid_attributes
        put :update, {:id => mobile_app.to_param, :mobile_app => valid_attributes}, valid_session
        response.should redirect_to(mobile_app)
      end
    end

    describe "with invalid params" do
      it "assigns the mobile_app as @mobile_app" do
        mobile_app = MobileApp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MobileApp.any_instance.stub(:save).and_return(false)
        put :update, {:id => mobile_app.to_param, :mobile_app => { "name" => "invalid value" }}, valid_session
        assigns(:mobile_app).should eq(mobile_app)
      end

      it "re-renders the 'edit' template" do
        mobile_app = MobileApp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MobileApp.any_instance.stub(:save).and_return(false)
        put :update, {:id => mobile_app.to_param, :mobile_app => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mobile_app" do
      mobile_app = MobileApp.create! valid_attributes
      expect {
        delete :destroy, {:id => mobile_app.to_param}, valid_session
      }.to change(MobileApp, :count).by(-1)
    end

    it "redirects to the mobile_apps list" do
      mobile_app = MobileApp.create! valid_attributes
      delete :destroy, {:id => mobile_app.to_param}, valid_session
      response.should redirect_to(mobile_apps_url)
    end
  end

end
